### ISSUE TITLE
Menpo3d- python 2.7-viewing a Mesh-error-GLib-GIO-Message: Using the ‘memory’ GSettings backend. Your settings will not be saved or shared with other applications.

### ISSUE THREAD

**Issue by 099-111-100-101-114-101-100** [menpo/menpo#809] opened 2017-09-06 10:31 UTC
Attempting to view a mesh via the following code:

import menpo3d.io as mio
mesh = mio.import_builtin_asset('james.obj')
mesh.view()

This produces the error message- 
GLib-GIO-Message: Using the ‘memory’ GSettings backend. Your settings will not be saved or shared with other applications.

However when the Rasterization Basics jupyter notebook is run,  Mayavi scene opens, displaying the mesh but with error messages which are shown in the attached image below (which can be zoomed in to hopefully)

![rasterization-basics](https://user-images.githubusercontent.com/31691969/30107501-d6ca00f0-92f6-11e7-9494-45606b87f231.jpg)

Thank you for any help you can give

**Comment by patricksnape** [comment] 2017-09-06 20:32
Sorry I'm a bit confused - there are two different things going on in that notebook - one is viewing a mesh using Mayavi - another is rasterizing using Cyrasterize. Cyrasterize and Mayavi do not play well together - there are a lot of issues with them ruining the OpenGL context for each other. I'm not sure that this notebook actually works as intended due to this.

**Comment by 099-111-100-101-114-101-100** [comment] 2017-09-07 11:59
Thank you for your reply. With regards to trying to run the same sample code outside of notebooks, downloaded as a python script and run through the command line, I get the error below :
''
ERROR:root:
Exception RuntimeError: RuntimeError('Framebuffer error: 36061 0x8CDD',) in 'cyrasterize.glrasterizer.GLScene.init_frame_buffer' ignored
ERROR:root: *** Error *** [invalid framebuffer operation] 1286
ERROR:root: *** Error *** [invalid framebuffer operation] 1286
ERROR:root: *** Error *** [invalid framebuffer operation] 1286
ERROR:root: *** Error *** [invalid framebuffer operation] 1286
Segmentation fault (core dumped)
''
And when I run code to simply view a mesh on its own:
error-GLib-GIO-Message: Using the ‘memory’ GSettings backend. Your settings will not be saved or shared with other applications.

**Comment by patricksnape** [comment] 2020-01-05 12:52
cyrasterize is no longer used - we now use a moderngl based rasterizer that should be better behaved - closing as I believe this is out of date

**Closed by patricksnape** 2020-01-05 12:52 UTC
